### ISSUE TITLE
video-format

### ISSUE THREAD

**Issue by sunzhongmeng** [antmicro/sdi-mipi-bridge-gateware#1]
video-format is one of 720p60, 1080p30, 1080p60,no other formats are supported2,e.g. 1080p50,720p50?

**Comment by robertszczepanski** [comment]
Hi @sunzhongmeng, you can find the list of all supported video formats in the Hardware chapter of [the SDI-MIPI Bridge documentation](https://antmicro.github.io/sdi-mipi-bridge/hardware.html#transmitter). Both 1080p50 and 720p50 that you mentioned are supported.

If you need more information, you can also find it in the [project documentation](https://antmicro.github.io/sdi-mipi-bridge/index.html).

**Comment by sunzhongmeng** [comment]
> Hi @sunzhongmeng, you can find the list of all supported video formats in the Hardware chapter of [the SDI-MIPI Bridge documentation](https://antmicro.github.io/sdi-mipi-bridge/hardware.html#transmitter). Both 1080p50 and 720p50 that you mentioned are supported.
> 
> If you need more information, you can also find it in the [project documentation](https://antmicro.github.io/sdi-mipi-bridge/index.html).


@robertszczepanski thank you very much! by the way , does it support  "ancillary data",how to extract "ancillary data" from GS2971A output stream?

**Comment by robertszczepanski** [comment]
@sunzhongmeng Even though the deserializer extracts ancillary data, this is not currently supported and it would require adding such feature to [the Linux kernel](https://github.com/antmicro/sdi-mipi-bridge-linux/), you can take a look at [the GS2971A driver](https://github.com/antmicro/sdi-mipi-bridge-linux/blob/main/nvidia/drivers/media/spi/gs2971a.c).

**Comment by sunzhongmeng** [comment]
> @sunzhongmeng Even though the deserializer extracts ancillary data, this is not currently supported and it would require adding such feature to [the Linux kernel](https://github.com/antmicro/sdi-mipi-bridge-linux/), you can take a look at [the GS2971A driver](https://github.com/antmicro/sdi-mipi-bridge-linux/blob/main/nvidia/drivers/media/spi/gs2971a.c).

Thank you,I got it.
